# Create a default fully qualified app name.
# We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
# If release name contains chart name it will be used as a full name.
{{- define "name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- printf .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

# https://github.com/helm/helm/issues/4535
{{- define "call-nested" }}
{{- $dot := index . 0 }}
{{- $subchart := index . 1 }}
{{- $template := index . 2 }}
{{- include $template (dict "Chart" (dict "Name" $subchart) "Values" (index $dot.Values $subchart) "Release" $dot.Release "Capabilities" $dot.Capabilities) }}
{{- end }}

{{- define "repo-tag" }}
{{- if .Values.banzaicloud.organization.name }}
{{- range .Values.banzaicloud.tags }}
{{- if regexMatch "^repo:" . }}
{{- . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- define "repo-user" }}
{{- if .Values.banzaicloud.organization.name }}
{{- range .Values.banzaicloud.tags }}
{{- if regexMatch "^repo:" . }}
{{- $repoFullName := regexReplaceAll "^repo:" . "" }}
{{- first (splitList "/" $repoFullName) }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- define "repo-name" }}
{{- if .Values.banzaicloud.organization.name }}
{{- range .Values.banzaicloud.tags }}
{{- if regexMatch "^repo:" . }}
{{- $repoFullName := regexReplaceAll "^repo:" . "" }}
{{- last (splitList "/" $repoFullName) }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
